1 to 0 update

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,6 +12,8 @@ jobs:
             - name: Failed Step
               run:   |
                    echo "I am going to fail"
-                   exit 1
+                   exit 0
+                #    exit 1 Fail
+                #  exit 0 Success
             - name: Say Goodbye
               run: echo "Goodbye! World"
