Functions

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,22 +1,23 @@
-name: 09 -Using Functions
-on: pull_request:
-    types: [opened, synchronize]
-    branches: [main]
+name: 09 - Using Functions
+on: 
+  push:
+  workflow_dispatch:
+
 jobs:
   job-1:
-    runs:on: ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
-        - name: Failing Step
-          run: exit 1
-        - name: I will be skipped
-          if: ${{ success() }}
-          run: echo "This will be skipped if the previous step fails"
-        - name: I will execute
-          if: ${{ failure() }}
-          run: echo "This will run if any previous step fails"
-        - name: I will execure
-          if: ${{ !cancelled() }}
-          run: echo "This will run if the workflow is not cancelled"
-        - name: I will execure on cancelled
-          if: ${{ cancelled()}}
-          run: echo "I will print if the workflow has been cancelled."
+      - name: Failing Step
+        run: exit 1
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "This will be skipped if the previous step fails"
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "This will run if any previous step fails"
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "This will run if the workflow is not cancelled"
+      - name: I will execute on cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled."
